FLAGS_DB = {
    "Monaco": {"nombre": "Mónaco", "nombre_en": "Monaco", "code": "mc", "grupo": "rojo_blanco_horizontal"},
    "Indonesia": {"nombre": "Indonesia", "nombre_en": "Indonesia", "code": "id", "grupo": "rojo_blanco_horizontal"},
    "Polonia": {"nombre": "Polonia", "nombre_en": "Poland", "code": "pl", "grupo": "rojo_blanco_horizontal"},
    "Singapur": {"nombre": "Singapur", "nombre_en": "Singapore", "code": "sg", "grupo": "rojo_blanco_horizontal"},
    "Austria": {"nombre": "Austria", "nombre_en": "Austria", "code": "at", "grupo": "rojo_blanco_horizontal"},
    "Malta": {"nombre": "Malta", "nombre_en": "Malta", "code": "mt", "grupo": "rojo_blanco_horizontal"},
    "Gibraltar": {"nombre": "Gibraltar", "nombre_en": "Gibraltar", "code": "gi", "grupo": "rojo_blanco_horizontal"},
    "Suiza": {"nombre": "Suiza", "nombre_en": "Switzerland", "code": "ch", "grupo": "rojo_blanco_horizontal"},
    "Rumania": {"nombre": "Rumania", "nombre_en": "Romania", "code": "ro", "grupo": "azul_amarillo_rojo_vertical"},
    "Chad": {"nombre": "Chad", "nombre_en": "Chad", "code": "td", "grupo": "azul_amarillo_rojo_vertical"},
    "Andorra": {"nombre": "Andorra", "nombre_en": "Andorra", "code": "ad", "grupo": "azul_amarillo_rojo_vertical"},
    "Moldavia": {"nombre": "Moldavia", "nombre_en": "Moldova", "code": "md", "grupo": "azul_amarillo_rojo_vertical"},
    "Belgica": {"nombre": "Bélgica", "nombre_en": "Belgium", "code": "be", "grupo": "azul_amarillo_rojo_vertical"},
    "Irlanda": {"nombre": "Irlanda", "nombre_en": "Ireland", "code": "ie", "grupo": "vertical_verde_blanco_naranja_rojo"},
    "Costa de Marfil": {"nombre": "Costa de Marfil", "nombre_en": "Ivory Coast", "code": "ci", "grupo": "vertical_verde_blanco_naranja_rojo"},
    "Italia": {"nombre": "Italia", "nombre_en": "Italy", "code": "it", "grupo": "vertical_verde_blanco_naranja_rojo"},
    "Mexico": {"nombre": "México", "nombre_en": "Mexico", "code": "mx", "grupo": "vertical_verde_blanco_naranja_rojo"},
    "Francia": {"nombre": "Francia", "nombre_en": "France", "code": "fr", "grupo": "rojo_blanco_azul_tiras"},
    "Guinea": {"nombre": "Guinea", "nombre_en": "Guinea", "code": "gn", "grupo": "panafricano_verde_amarillo_rojo"},
    "Mali": {"nombre": "Malí", "nombre_en": "Mali", "code": "ml", "grupo": "panafricano_verde_amarillo_rojo"},
    "Senegal": {"nombre": "Senegal", "nombre_en": "Senegal", "code": "sn", "grupo": "panafricano_verde_amarillo_rojo"},
    "Camerun": {"nombre": "Camerún", "nombre_en": "Cameroon", "code": "cm", "grupo": "panafricano_verde_amarillo_rojo"},
    "Peru": {"nombre": "Perú", "nombre_en": "Peru", "code": "pe", "grupo": "vertical_verde_blanco_naranja_rojo"},
    "Colombia": {"nombre": "Colombia", "nombre_en": "Colombia", "code": "co", "grupo": "amarillo_azul_rojo_horizontal"},
    "Ecuador": {"nombre": "Ecuador", "nombre_en": "Ecuador", "code": "ec", "grupo": "amarillo_azul_rojo_horizontal"},
    "Venezuela": {"nombre": "Venezuela", "nombre_en": "Venezuela", "code": "ve", "grupo": "amarillo_azul_rojo_horizontal"},
    "Argentina": {"nombre": "Argentina", "nombre_en": "Argentina", "code": "ar", "grupo": "azul_celeste_blanco"},
    "Uruguay": {"nombre": "Uruguay", "nombre_en": "Uruguay", "code": "uy", "grupo": "azul_celeste_blanco"},
    "El Salvador": {"nombre": "El Salvador", "nombre_en": "El Salvador", "code": "sv", "grupo": "azul_celeste_blanco"},
    "Honduras": {"nombre": "Honduras", "nombre_en": "Honduras", "code": "hn", "grupo": "azul_celeste_blanco"},
    "Nicaragua": {"nombre": "Nicaragua", "nombre_en": "Nicaragua", "code": "ni", "grupo": "azul_celeste_blanco"},
    "Guatemala": {"nombre": "Guatemala", "nombre_en": "Guatemala", "code": "gt", "grupo": "azul_celeste_blanco"},
    "Grecia": {"nombre": "Grecia", "nombre_en": "Greece", "code": "gr", "grupo": "azul_celeste_blanco"},
    "Israel": {"nombre": "Israel", "nombre_en": "Israel", "code": "il", "grupo": "azul_celeste_blanco"},
    "San Marino": {"nombre": "San Marino", "nombre_en": "San Marino", "code": "sm", "grupo": "azul_celeste_blanco"},
    "Reino Unido": {"nombre": "Reino Unido", "nombre_en": "United Kingdom", "code": "gb", "grupo": "union_jack_style"},
    "Australia": {"nombre": "Australia", "nombre_en": "Australia", "code": "au", "grupo": "union_jack_style"},
    "Nueva Zelanda": {"nombre": "Nueva Zelanda", "nombre_en": "New Zealand", "code": "nz", "grupo": "union_jack_style"},
    "Tuvalu": {"nombre": "Tuvalu", "nombre_en": "Tuvalu", "code": "tv", "grupo": "union_jack_style"},
    "Fiyi": {"nombre": "Fiyi", "nombre_en": "Fiji", "code": "fj", "grupo": "union_jack_style"},
    "Dinamarca": {"nombre": "Dinamarca", "nombre_en": "Denmark", "code": "dk", "grupo": "cruz_escandinava"},
    "Noruega": {"nombre": "Noruega", "nombre_en": "Norway", "code": "no", "grupo": "cruz_escandinava"},
    "Suecia": {"nombre": "Suecia", "nombre_en": "Sweden", "code": "se", "grupo": "cruz_escandinava"},
    "Finlandia": {"nombre": "Finlandia", "nombre_en": "Finland", "code": "fi", "grupo": "cruz_escandinava"},
    "Islandia": {"nombre": "Islandia", "nombre_en": "Iceland", "code": "is", "grupo": "cruz_escandinava"},
    "Paises Bajos": {"nombre": "Países Bajos", "nombre_en": "Netherlands", "code": "nl", "grupo": "rojo_blanco_azul_tiras"},
    "Luxemburgo": {"nombre": "Luxemburgo", "nombre_en": "Luxembourg", "code": "lu", "grupo": "rojo_blanco_azul_tiras"},
    "Rusia": {"nombre": "Rusia", "nombre_en": "Russia", "code": "ru", "grupo": "rojo_blanco_azul_tiras"},
    "Croacia": {"nombre": "Croacia", "nombre_en": "Croatia", "code": "hr", "grupo": "rojo_blanco_azul_tiras"},
    "Serbia": {"nombre": "Serbia", "nombre_en": "Serbia", "code": "rs", "grupo": "rojo_blanco_azul_tiras"},
    "Eslovenia": {"nombre": "Eslovenia", "nombre_en": "Slovenia", "code": "si", "grupo": "rojo_blanco_azul_tiras"},
    "Eslovaquia": {"nombre": "Eslovaquia", "nombre_en": "Slovakia", "code": "sk", "grupo": "rojo_blanco_azul_tiras"},
    "Tailandia": {"nombre": "Tailandia", "nombre_en": "Thailand", "code": "th", "grupo": "rojo_blanco_azul_tiras"},
    "Costa Rica": {"nombre": "Costa Rica", "nombre_en": "Costa Rica", "code": "cr", "grupo": "rojo_blanco_azul_tiras"},
    "Japon": {"nombre": "Japón", "nombre_en": "Japan", "code": "jp", "grupo": "circulo_central"},
    "Palau": {"nombre": "Palau", "nombre_en": "Palau", "code": "pw", "grupo": "circulo_central"},
    "Bangladesh": {"nombre": "Bangladesh", "nombre_en": "Bangladesh", "code": "bd", "grupo": "circulo_central"},
    "Niger": {"nombre": "Níger", "nombre_en": "Niger", "code": "ne", "grupo": "circulo_central"},
    "India": {"nombre": "India", "nombre_en": "India", "code": "in", "grupo": "tres_franjas_horizontales"},
    "Corea del Sur": {"nombre": "Corea del Sur", "nombre_en": "South Korea", "code": "kr", "grupo": "circulo_central"},
    "Estados Unidos": {"nombre": "Estados Unidos", "nombre_en": "United States", "code": "us", "grupo": "estrellas_y_barras"},
    "Liberia": {"nombre": "Liberia", "nombre_en": "Liberia", "code": "lr", "grupo": "estrellas_y_barras"},
    "Malasia": {"nombre": "Malasia", "nombre_en": "Malaysia", "code": "my", "grupo": "estrellas_y_barras"},
    "Cuba": {"nombre": "Cuba", "nombre_en": "Cuba", "code": "cu", "grupo": "estrellas_y_barras"},
    "Puerto Rico": {"nombre": "Puerto Rico", "nombre_en": "Puerto Rico", "code": "pr", "grupo": "estrellas_y_barras"},
    "Alemania": {"nombre": "Alemania", "nombre_en": "Germany", "code": "de", "grupo": "negro_rojo_amarillo"},
    "Angola": {"nombre": "Angola", "nombre_en": "Angola", "code": "ao", "grupo": "negro_rojo_amarillo"},
    "Uganda": {"nombre": "Uganda", "nombre_en": "Uganda", "code": "ug", "grupo": "negro_rojo_amarillo"},
    "Egipto": {"nombre": "Egipto", "nombre_en": "Egypt", "code": "eg", "grupo": "arabe_tricolor_horizontal"},
    "Siria": {"nombre": "Siria", "nombre_en": "Syria", "code": "sy", "grupo": "arabe_tricolor_horizontal"},
    "Irak": {"nombre": "Irak", "nombre_en": "Iraq", "code": "iq", "grupo": "arabe_tricolor_horizontal"},
    "Yemen": {"nombre": "Yemen", "nombre_en": "Yemen", "code": "ye", "grupo": "arabe_tricolor_horizontal"},
    "Sudan": {"nombre": "Sudán", "nombre_en": "Sudan", "code": "sd", "grupo": "arabe_tricolor_horizontal"},
    "Jordania": {"nombre": "Jordania", "nombre_en": "Jordan", "code": "jo", "grupo": "arabe_tricolor_horizontal"},
    "Palestina": {"nombre": "Palestina", "nombre_en": "Palestine", "code": "ps", "grupo": "arabe_tricolor_horizontal"},
    "Emiratos Arabes Unidos": {"nombre": "Emiratos Árabes Unidos", "nombre_en": "United Arab Emirates", "code": "ae", "grupo": "arabe_tricolor_horizontal"},
    "Kuwait": {"nombre": "Kuwait", "nombre_en": "Kuwait", "code": "kw", "grupo": "arabe_tricolor_horizontal"},
    "Bolivia": {"nombre": "Bolivia", "nombre_en": "Bolivia", "code": "bo", "grupo": "panafricano_verde_amarillo_rojo"},
    "Ghana": {"nombre": "Ghana", "nombre_en": "Ghana", "code": "gh", "grupo": "panafricano_verde_amarillo_rojo"},
    "Congo": {"nombre": "Congo", "nombre_en": "Congo", "code": "cg", "grupo": "panafricano_verde_amarillo_rojo"},
    "Benin": {"nombre": "Benín", "nombre_en": "Benin", "code": "bj", "grupo": "panafricano_verde_amarillo_rojo"},
    "Togo": {"nombre": "Togo", "nombre_en": "Togo", "code": "tg", "grupo": "panafricano_verde_amarillo_rojo"},
    "Nigeria": {"nombre": "Nigeria", "nombre_en": "Nigeria", "code": "ng", "grupo": "verde_blanco_horizontal"},
    "Pakistan": {"nombre": "Pakistán", "nombre_en": "Pakistan", "code": "pk", "grupo": "verde_blanco_horizontal"},
    "Arabia Saudita": {"nombre": "Arabia Saudita", "nombre_en": "Saudi Arabia", "code": "sa", "grupo": "verde_blanco_horizontal"},
    "Argelia": {"nombre": "Argelia", "nombre_en": "Algeria", "code": "dz", "grupo": "verde_blanco_horizontal"},
    "Mauritania": {"nombre": "Mauritania", "nombre_en": "Mauritania", "code": "mr", "grupo": "verde_blanco_horizontal"},
    "Estonia": {"nombre": "Estonia", "nombre_en": "Estonia", "code": "ee", "grupo": "tres_franjas_horizontales"},
    "Letonia": {"nombre": "Letonia", "nombre_en": "Latvia", "code": "lv", "grupo": "tres_franjas_horizontales"},
    "Lituania": {"nombre": "Lituania", "nombre_en": "Lithuania", "code": "lt", "grupo": "tres_franjas_horizontales"},
    "Bulgaria": {"nombre": "Bulgaria", "nombre_en": "Bulgaria", "code": "bg", "grupo": "tres_franjas_horizontales"},
    "Hungria": {"nombre": "Hungría", "nombre_en": "Hungary", "code": "hu", "grupo": "tres_franjas_horizontales"},
    "Sierra Leona": {"nombre": "Sierra Leona", "nombre_en": "Sierra Leone", "code": "sl", "grupo": "tres_franjas_horizontales"},
    "Gabon": {"nombre": "Gabón", "nombre_en": "Gabon", "code": "ga", "grupo": "tres_franjas_horizontales"},
    "Brasil": {"nombre": "Brasil", "nombre_en": "Brazil", "code": "br", "grupo": "soles_y_estrellas"},
    "Cabo Verde": {"nombre": "Cabo Verde", "nombre_en": "Cape Verde", "code": "cv", "grupo": "soles_y_estrellas"},
    "Kosovo": {"nombre": "Kosovo", "nombre_en": "Kosovo", "code": "xk", "grupo": "soles_y_estrellas"},
    "Bosnia y Herzegovina": {"nombre": "Bosnia y Herzegovina", "nombre_en": "Bosnia and Herzegovina", "code": "ba", "grupo": "soles_y_estrellas"},
    "Micronesia": {"nombre": "Micronesia", "nombre_en": "Micronesia", "code": "fm", "grupo": "soles_y_estrellas"},
    "Turquia": {"nombre": "Turquía", "nombre_en": "Turkey", "code": "tr", "grupo": "media_luna_estrella"},
    "Tunez": {"nombre": "Túnez", "nombre_en": "Tunisia", "code": "tn", "grupo": "media_luna_estrella"},
    "Libia": {"nombre": "Libia", "nombre_en": "Libya", "code": "ly", "grupo": "media_luna_estrella"},
    "Azerbaiyan": {"nombre": "Azerbaiyán", "nombre_en": "Azerbaijan", "code": "az", "grupo": "media_luna_estrella"},
    "China": {"nombre": "China", "nombre_en": "China", "code": "cn", "grupo": "rojo_unicolor_o_predominante"},
    "Vietnam": {"nombre": "Vietnam", "nombre_en": "Vietnam", "code": "vn", "grupo": "rojo_unicolor_o_predominante"},
    "Albania": {"nombre": "Albania", "nombre_en": "Albania", "code": "al", "grupo": "rojo_unicolor_o_predominante"},
    "Montenegro": {"nombre": "Montenegro", "nombre_en": "Montenegro", "code": "me", "grupo": "rojo_unicolor_o_predominante"},
    "Marruecos": {"nombre": "Marruecos", "nombre_en": "Morocco", "code": "ma", "grupo": "rojo_unicolor_o_predominante"},
    "Kirguistan": {"nombre": "Kirguistán", "nombre_en": "Kyrgyzstan", "code": "kg", "grupo": "rojo_unicolor_o_predominante"},
    "Somalia": {"nombre": "Somalia", "nombre_en": "Somalia", "code": "so", "grupo": "azul_unicolor_o_predominante"},
    "Republica Democratica del Congo": {"nombre": "R. D. del Congo", "nombre_en": "Democratic Republic of the Congo", "code": "cd", "grupo": "azul_unicolor_o_predominante"},
    "Nauru": {"nombre": "Nauru", "nombre_en": "Nauru", "code": "nr", "grupo": "azul_unicolor_o_predominante"},
    "Canada": {"nombre": "Canadá", "nombre_en": "Canada", "code": "ca", "grupo": "otros_disenos"},
    "Nepal": {"nombre": "Nepal", "nombre_en": "Nepal", "code": "np", "grupo": "otros_disenos"},
    "Butan": {"nombre": "Bután", "nombre_en": "Bhutan", "code": "bt", "grupo": "otros_disenos"},
    "Sri Lanka": {"nombre": "Sri Lanka", "nombre_en": "Sri Lanka", "code": "lk", "grupo": "otros_disenos"},
    "Mongolia": {"nombre": "Mongolia", "nombre_en": "Mongolia", "code": "mn", "grupo": "otros_disenos"},
    "Camboya": {"nombre": "Camboya", "nombre_en": "Cambodia", "code": "kh", "grupo": "otros_disenos"},
    "Laos": {"nombre": "Laos", "nombre_en": "Laos", "code": "la", "grupo": "otros_disenos"},
    "Espana": {"nombre": "España", "nombre_en": "Spain", "code": "es", "grupo": "tres_franjas_horizontales"},
    "Portugal": {"nombre": "Portugal", "nombre_en": "Portugal", "code": "pt", "grupo": "otros_disenos"},
    "Chipre": {"nombre": "Chipre", "nombre_en": "Cyprus", "code": "cy", "grupo": "otros_disenos"},
    "República Checa": {"nombre": "República Checa", "nombre_en": "Czech Republic", "code": "cz", "grupo": "otros_disenos"},
    "Ucrania": {"nombre": "Ucrania", "nombre_en": "Ukraine", "code": "ua", "grupo": "azul_unicolor_o_predominante"},
    "Bielorrusia": {"nombre": "Bielorrusia", "nombre_en": "Belarus", "code": "by", "grupo": "otros_disenos"},
    "Macedonia del Norte": {"nombre": "Macedonia del Norte", "nombre_en": "North Macedonia", "code": "mk", "grupo": "otros_disenos"},
    "Georgia": {"nombre": "Georgia", "nombre_en": "Georgia", "code": "ge", "grupo": "otros_disenos"},
    "Armenia": {"nombre": "Armenia", "nombre_en": "Armenia", "code": "am", "grupo": "tres_franjas_horizontales"},
    "Libano": {"nombre": "Líbano", "nombre_en": "Lebanon", "code": "lb", "grupo": "otros_disenos"},
    "Oman": {"nombre": "Omán", "nombre_en": "Oman", "code": "om", "grupo": "arabe_tricolor_horizontal"},
    "Qatar": {"nombre": "Catar", "nombre_en": "Qatar", "code": "qa", "grupo": "otros_disenos"},
    "Bahrein": {"nombre": "Baréin", "nombre_en": "Bahrain", "code": "bh", "grupo": "otros_disenos"},
    "Iran": {"nombre": "Irán", "nombre_en": "Iran", "code": "ir", "grupo": "tres_franjas_horizontales"},
    "Kazajistan": {"nombre": "Kazajistán", "nombre_en": "Kazakhstan", "code": "kz", "grupo": "azul_unicolor_o_predominante"},
    "Uzbekistan": {"nombre": "Uzbekistán", "nombre_en": "Uzbekistan", "code": "uz", "grupo": "verde_blanco_horizontal"},
    "Turkmenistan": {"nombre": "Turkmenistán", "nombre_en": "Turkmenistan", "code": "tm", "grupo": "verde_blanco_horizontal"},
    "Tayikistan": {"nombre": "Tayikistán", "nombre_en": "Tajikistan", "code": "tj", "grupo": "verde_blanco_horizontal"},
    "Afganistan": {"nombre": "Afganistán", "nombre_en": "Afghanistan", "code": "af", "grupo": "otros_disenos"},
    "Maldivas": {"nombre": "Maldivas", "nombre_en": "Maldives", "code": "mv", "grupo": "otros_disenos"},
    "Corea del Norte": {"nombre": "Corea del Norte", "nombre_en": "North Korea", "code": "kp", "grupo": "otros_disenos"},
    "Taiwan": {"nombre": "Taiwán", "nombre_en": "Taiwan", "code": "tw", "grupo": "otros_disenos"},
    "Filipinas": {"nombre": "Filipinas", "nombre_en": "Philippines", "code": "ph", "grupo": "otros_disenos"},
    "Brunei": {"nombre": "Brunéi", "nombre_en": "Brunei", "code": "bn", "grupo": "otros_disenos"},
    "Timor Oriental": {"nombre": "Timor Oriental", "nombre_en": "East Timor", "code": "tl", "grupo": "otros_disenos"},
    "Papua Nueva Guinea": {"nombre": "Papua Nueva Guinea", "nombre_en": "Papua New Guinea", "code": "pg", "grupo": "otros_disenos"},
    "Islas Salomon": {"nombre": "Islas Salomón", "nombre_en": "Solomon Islands", "code": "sb", "grupo": "soles_y_estrellas"},
    "Vanuatu": {"nombre": "Vanuatu", "nombre_en": "Vanuatu", "code": "vu", "grupo": "otros_disenos"},
    "Tonga": {"nombre": "Tonga", "nombre_en": "Tonga", "code": "to", "grupo": "rojo_unicolor_o_predominante"},
    "Samoa": {"nombre": "Samoa", "nombre_en": "Samoa", "code": "ws", "grupo": "rojo_unicolor_o_predominante"},
    "Kiribati": {"nombre": "Kiribati", "nombre_en": "Kiribati", "code": "ki", "grupo": "otros_disenos"},
    "Islas Marshall": {"nombre": "Islas Marshall", "nombre_en": "Marshall Islands", "code": "mh", "grupo": "otros_disenos"},
    "Sahara Occidental": {"nombre": "Sahara Occidental", "nombre_en": "Western Sahara", "code": "eh", "grupo": "arabe_tricolor_horizontal"},
    "Sudan del Sur": {"nombre": "Sudán del Sur", "nombre_en": "South Sudan", "code": "ss", "grupo": "arabe_tricolor_horizontal"},
    "Gambia": {"nombre": "Gambia", "nombre_en": "Gambia", "code": "gm", "grupo": "tres_franjas_horizontales"},
    "Guinea-Bissau": {"nombre": "Guinea-Bisáu", "nombre_en": "Guinea-Bissau", "code": "gw", "grupo": "panafricano_verde_amarillo_rojo"},
    "Republica Centroafricana": {"nombre": "R. Centroafricana", "nombre_en": "Central African Republic", "code": "cf", "grupo": "otros_disenos"},
    "Guinea Ecuatorial": {"nombre": "Guinea Ecuatorial", "nombre_en": "Equatorial Guinea", "code": "gq", "grupo": "tres_franjas_horizontales"},
    "Santo Tome y Principe": {"nombre": "Santo Tomé y Príncipe", "nombre_en": "São Tomé and Príncipe", "code": "st", "grupo": "otros_disenos"},
    "Eritrea": {"nombre": "Eritrea", "nombre_en": "Eritrea", "code": "er", "grupo": "otros_disenos"},
    "Etiopia": {"nombre": "Etiopía", "nombre_en": "Ethiopia", "code": "et", "grupo": "otros_disenos"},
    "Yibuti": {"nombre": "Yibuti", "nombre_en": "Djibouti", "code": "dj", "grupo": "otros_disenos"},
    "Kenia": {"nombre": "Kenia", "nombre_en": "Kenya", "code": "ke", "grupo": "otros_disenos"},
    "Ruanda": {"nombre": "Ruanda", "nombre_en": "Rwanda", "code": "rw", "grupo": "otros_disenos"},
    "Burundi": {"nombre": "Burundi", "nombre_en": "Burundi", "code": "bi", "grupo": "otros_disenos"},
    "Tanzania": {"nombre": "Tanzania", "nombre_en": "Tanzania", "code": "tz", "grupo": "otros_disenos"},
    "Seychelles": {"nombre": "Seychelles", "nombre_en": "Seychelles", "code": "sc", "grupo": "otros_disenos"},
    "Zambia": {"nombre": "Zambia", "nombre_en": "Zambia", "code": "zm", "grupo": "otros_disenos"},
    "Malawi": {"nombre": "Malaui", "nombre_en": "Malawi", "code": "mw", "grupo": "tres_franjas_horizontales"},
    "Mozambique": {"nombre": "Mozambique", "nombre_en": "Mozambique", "code": "mz", "grupo": "otros_disenos"},
    "Zimbabwe": {"nombre": "Zimbabue", "nombre_en": "Zimbabwe", "code": "zw", "grupo": "otros_disenos"},
    "Botswana": {"nombre": "Botsuana", "nombre_en": "Botswana", "code": "bw", "grupo": "tres_franjas_horizontales"},
    "Namibia": {"nombre": "Namibia", "nombre_en": "Namibia", "code": "na", "grupo": "otros_disenos"},
    "Sudafrica": {"nombre": "Sudáfrica", "nombre_en": "South Africa", "code": "za", "grupo": "otros_disenos"},
    "Lesoto": {"nombre": "Lesoto", "nombre_en": "Lesotho", "code": "ls", "grupo": "tres_franjas_horizontales"},
    "Eswatini": {"nombre": "Suazilandia", "nombre_en": "Eswatini", "code": "sz", "grupo": "otros_disenos"},
    "Madagascar": {"nombre": "Madagascar", "nombre_en": "Madagascar", "code": "mg", "grupo": "otros_disenos"},
    "Mauricio": {"nombre": "Mauricio", "nombre_en": "Mauritius", "code": "mu", "grupo": "tres_franjas_horizontales"},
    "Comoras": {"nombre": "Comoras", "nombre_en": "Comoros", "code": "km", "grupo": "otros_disenos"},
    "Belice": {"nombre": "Belice", "nombre_en": "Belize", "code": "bz", "grupo": "otros_disenos"},
    "Panama": {"nombre": "Panamá", "nombre_en": "Panama", "code": "pa", "grupo": "otros_disenos"},
    "Bahamas": {"nombre": "Bahamas", "nombre_en": "Bahamas", "code": "bs", "grupo": "otros_disenos"},
    "Haiti": {"nombre": "Haití", "nombre_en": "Haiti", "code": "ht", "grupo": "otros_disenos"},
    "Republica Dominicana": {"nombre": "R. Dominicana", "nombre_en": "Dominican Republic", "code": "do", "grupo": "otros_disenos"},
    "San Cristobal y Nieves": {"nombre": "San Cristóbal y Nieves", "nombre_en": "Saint Kitts and Nevis", "code": "kn", "grupo": "otros_disenos"},
    "Antigua y Barbuda": {"nombre": "Antigua y Barbuda", "nombre_en": "Antigua and Barbuda", "code": "ag", "grupo": "otros_disenos"},
    "Dominica": {"nombre": "Dominica", "nombre_en": "Dominica", "code": "dm", "grupo": "otros_disenos"},
    "Santa Lucia": {"nombre": "Santa Lucía", "nombre_en": "Saint Lucia", "code": "lc", "grupo": "otros_disenos"},
    "San Vicente y las Granadinas": {"nombre": "San Vicente y Granadinas", "nombre_en": "Saint Vincent and the Grenadines", "code": "vc", "grupo": "otros_disenos"},
    "Barbados": {"nombre": "Barbados", "nombre_en": "Barbados", "code": "bb", "grupo": "otros_disenos"},
    "Granada": {"nombre": "Granada", "nombre_en": "Grenada", "code": "gd", "grupo": "otros_disenos"},
    "Trinidad y Tobago": {"nombre": "Trinidad y Tobago", "nombre_en": "Trinidad and Tobago", "code": "tt", "grupo": "otros_disenos"},
    "Guyana": {"nombre": "Guyana", "nombre_en": "Guyana", "code": "gy", "grupo": "otros_disenos"},
    "Surinam": {"nombre": "Surinam", "nombre_en": "Suriname", "code": "sr", "grupo": "otros_disenos"},
    "Chile": {"nombre": "Chile", "nombre_en": "Chile", "code": "cl", "grupo": "otros_disenos"},
}
