FLAGS_DB = {
    "Monaco": {"nombre": "Mónaco", "code": "mc", "grupo": "rojo_blanco_horizontal"},
    "Indonesia": {"nombre": "Indonesia", "code": "id", "grupo": "rojo_blanco_horizontal"},
    "Polonia": {"nombre": "Polonia", "code": "pl", "grupo": "rojo_blanco_horizontal"},
    "Singapur": {"nombre": "Singapur", "code": "sg", "grupo": "rojo_blanco_horizontal"},
    "Austria": {"nombre": "Austria", "code": "at", "grupo": "rojo_blanco_horizontal"},
    "Malta": {"nombre": "Malta", "code": "mt", "grupo": "rojo_blanco_horizontal"},
    "Gibraltar": {"nombre": "Gibraltar", "code": "gi", "grupo": "rojo_blanco_horizontal"},
    "Suiza": {"nombre": "Suiza", "code": "ch", "grupo": "rojo_blanco_horizontal"},
    "Rumania": {"nombre": "Rumania", "code": "ro", "grupo": "azul_amarillo_rojo_vertical"},
    "Chad": {"nombre": "Chad", "code": "td", "grupo": "azul_amarillo_rojo_vertical"},
    "Andorra": {"nombre": "Andorra", "code": "ad", "grupo": "azul_amarillo_rojo_vertical"},
    "Moldavia": {"nombre": "Moldavia", "code": "md", "grupo": "azul_amarillo_rojo_vertical"},
    "Belgica": {"nombre": "Bélgica", "code": "be", "grupo": "azul_amarillo_rojo_vertical"},
    "Irlanda": {"nombre": "Irlanda", "code": "ie", "grupo": "vertical_verde_blanco_naranja_rojo"},
    "Costa de Marfil": {"nombre": "Costa de Marfil", "code": "ci", "grupo": "vertical_verde_blanco_naranja_rojo"},
    "Italia": {"nombre": "Italia", "code": "it", "grupo": "vertical_verde_blanco_naranja_rojo"},
    "Mexico": {"nombre": "México", "code": "mx", "grupo": "vertical_verde_blanco_naranja_rojo"},
    "Francia": {"nombre": "Francia", "code": "fr", "grupo": "rojo_blanco_azul_tiras"},
    "Guinea": {"nombre": "Guinea", "code": "gn", "grupo": "panafricano_verde_amarillo_rojo"},
    "Mali": {"nombre": "Malí", "code": "ml", "grupo": "panafricano_verde_amarillo_rojo"},
    "Senegal": {"nombre": "Senegal", "code": "sn", "grupo": "panafricano_verde_amarillo_rojo"},
    "Camerun": {"nombre": "Camerún", "code": "cm", "grupo": "panafricano_verde_amarillo_rojo"},
    "Peru": {"nombre": "Perú", "code": "pe", "grupo": "vertical_verde_blanco_naranja_rojo"},
    "Colombia": {"nombre": "Colombia", "code": "co", "grupo": "amarillo_azul_rojo_horizontal"},
    "Ecuador": {"nombre": "Ecuador", "code": "ec", "grupo": "amarillo_azul_rojo_horizontal"},
    "Venezuela": {"nombre": "Venezuela", "code": "ve", "grupo": "amarillo_azul_rojo_horizontal"},
    "Argentina": {"nombre": "Argentina", "code": "ar", "grupo": "azul_celeste_blanco"},
    "Uruguay": {"nombre": "Uruguay", "code": "uy", "grupo": "azul_celeste_blanco"},
    "El Salvador": {"nombre": "El Salvador", "code": "sv", "grupo": "azul_celeste_blanco"},
    "Honduras": {"nombre": "Honduras", "code": "hn", "grupo": "azul_celeste_blanco"},
    "Nicaragua": {"nombre": "Nicaragua", "code": "ni", "grupo": "azul_celeste_blanco"},
    "Guatemala": {"nombre": "Guatemala", "code": "gt", "grupo": "azul_celeste_blanco"},
    "Grecia": {"nombre": "Grecia", "code": "gr", "grupo": "azul_celeste_blanco"},
    "Israel": {"nombre": "Israel", "code": "il", "grupo": "azul_celeste_blanco"},
    "San Marino": {"nombre": "San Marino", "code": "sm", "grupo": "azul_celeste_blanco"},
    "Reino Unido": {"nombre": "Reino Unido", "code": "gb", "grupo": "union_jack_style"},
    "Australia": {"nombre": "Australia", "code": "au", "grupo": "union_jack_style"},
    "Nueva Zelanda": {"nombre": "Nueva Zelanda", "code": "nz", "grupo": "union_jack_style"},
    "Tuvalu": {"nombre": "Tuvalu", "code": "tv", "grupo": "union_jack_style"},
    "Fiyi": {"nombre": "Fiyi", "code": "fj", "grupo": "union_jack_style"},
    "Dinamarca": {"nombre": "Dinamarca", "code": "dk", "grupo": "cruz_escandinava"},
    "Noruega": {"nombre": "Noruega", "code": "no", "grupo": "cruz_escandinava"},
    "Suecia": {"nombre": "Suecia", "code": "se", "grupo": "cruz_escandinava"},
    "Finlandia": {"nombre": "Finlandia", "code": "fi", "grupo": "cruz_escandinava"},
    "Islandia": {"nombre": "Islandia", "code": "is", "grupo": "cruz_escandinava"},
    "Paises Bajos": {"nombre": "Países Bajos", "code": "nl", "grupo": "rojo_blanco_azul_tiras"},
    "Luxemburgo": {"nombre": "Luxemburgo", "code": "lu", "grupo": "rojo_blanco_azul_tiras"},
    "Rusia": {"nombre": "Rusia", "code": "ru", "grupo": "rojo_blanco_azul_tiras"},
    "Croacia": {"nombre": "Croacia", "code": "hr", "grupo": "rojo_blanco_azul_tiras"},
    "Serbia": {"nombre": "Serbia", "code": "rs", "grupo": "rojo_blanco_azul_tiras"},
    "Eslovenia": {"nombre": "Eslovenia", "code": "si", "grupo": "rojo_blanco_azul_tiras"},
    "Eslovaquia": {"nombre": "Eslovaquia", "code": "sk", "grupo": "rojo_blanco_azul_tiras"},
    "Tailandia": {"nombre": "Tailandia", "code": "th", "grupo": "rojo_blanco_azul_tiras"},
    "Costa Rica": {"nombre": "Costa Rica", "code": "cr", "grupo": "rojo_blanco_azul_tiras"},
    "Japon": {"nombre": "Japón", "code": "jp", "grupo": "circulo_central"},
    "Palau": {"nombre": "Palau", "code": "pw", "grupo": "circulo_central"},
    "Bangladesh": {"nombre": "Bangladesh", "code": "bd", "grupo": "circulo_central"},
    "Niger": {"nombre": "Níger", "code": "ne", "grupo": "circulo_central"},
    "India": {"nombre": "India", "code": "in", "grupo": "tres_franjas_horizontales"},
    "Corea del Sur": {"nombre": "Corea del Sur", "code": "kr", "grupo": "circulo_central"},
    "Estados Unidos": {"nombre": "Estados Unidos", "code": "us", "grupo": "estrellas_y_barras"},
    "Liberia": {"nombre": "Liberia", "code": "lr", "grupo": "estrellas_y_barras"},
    "Malasia": {"nombre": "Malasia", "code": "my", "grupo": "estrellas_y_barras"},
    "Cuba": {"nombre": "Cuba", "code": "cu", "grupo": "estrellas_y_barras"},
    "Puerto Rico": {"nombre": "Puerto Rico", "code": "pr", "grupo": "estrellas_y_barras"},
    "Alemania": {"nombre": "Alemania", "code": "de", "grupo": "negro_rojo_amarillo"},
    "Angola": {"nombre": "Angola", "code": "ao", "grupo": "negro_rojo_amarillo"},
    "Uganda": {"nombre": "Uganda", "code": "ug", "grupo": "negro_rojo_amarillo"},
    "Egipto": {"nombre": "Egipto", "code": "eg", "grupo": "arabe_tricolor_horizontal"},
    "Siria": {"nombre": "Siria", "code": "sy", "grupo": "arabe_tricolor_horizontal"},
    "Irak": {"nombre": "Irak", "code": "iq", "grupo": "arabe_tricolor_horizontal"},
    "Yemen": {"nombre": "Yemen", "code": "ye", "grupo": "arabe_tricolor_horizontal"},
    "Sudan": {"nombre": "Sudán", "code": "sd", "grupo": "arabe_tricolor_horizontal"},
    "Jordania": {"nombre": "Jordania", "code": "jo", "grupo": "arabe_tricolor_horizontal"},
    "Palestina": {"nombre": "Palestina", "code": "ps", "grupo": "arabe_tricolor_horizontal"},
    "Emiratos Arabes Unidos": {"nombre": "Emiratos Árabes Unidos", "code": "ae", "grupo": "arabe_tricolor_horizontal"},
    "Kuwait": {"nombre": "Kuwait", "code": "kw", "grupo": "arabe_tricolor_horizontal"},
    "Bolivia": {"nombre": "Bolivia", "code": "bo", "grupo": "panafricano_verde_amarillo_rojo"},
    "Ghana": {"nombre": "Ghana", "code": "gh", "grupo": "panafricano_verde_amarillo_rojo"},
    "Congo": {"nombre": "Congo", "code": "cg", "grupo": "panafricano_verde_amarillo_rojo"},
    "Benin": {"nombre": "Benín", "code": "bj", "grupo": "panafricano_verde_amarillo_rojo"},
    "Togo": {"nombre": "Togo", "code": "tg", "grupo": "panafricano_verde_amarillo_rojo"},
    "Nigeria": {"nombre": "Nigeria", "code": "ng", "grupo": "verde_blanco_horizontal"},
    "Pakistan": {"nombre": "Pakistán", "code": "pk", "grupo": "verde_blanco_horizontal"},
    "Arabia Saudita": {"nombre": "Arabia Saudita", "code": "sa", "grupo": "verde_blanco_horizontal"},
    "Argelia": {"nombre": "Argelia", "code": "dz", "grupo": "verde_blanco_horizontal"},
    "Mauritania": {"nombre": "Mauritania", "code": "mr", "grupo": "verde_blanco_horizontal"},
    "Estonia": {"nombre": "Estonia", "code": "ee", "grupo": "tres_franjas_horizontales"},
    "Letonia": {"nombre": "Letonia", "code": "lv", "grupo": "tres_franjas_horizontales"},
    "Lituania": {"nombre": "Lituania", "code": "lt", "grupo": "tres_franjas_horizontales"},
    "Bulgaria": {"nombre": "Bulgaria", "code": "bg", "grupo": "tres_franjas_horizontales"},
    "Hungria": {"nombre": "Hungría", "code": "hu", "grupo": "tres_franjas_horizontales"},
    "Sierra Leona": {"nombre": "Sierra Leona", "code": "sl", "grupo": "tres_franjas_horizontales"},
    "Gabon": {"nombre": "Gabón", "code": "ga", "grupo": "tres_franjas_horizontales"},
    "Brasil": {"nombre": "Brasil", "code": "br", "grupo": "soles_y_estrellas"},
    "Cabo Verde": {"nombre": "Cabo Verde", "code": "cv", "grupo": "soles_y_estrellas"},
    "Kosovo": {"nombre": "Kosovo", "code": "xk", "grupo": "soles_y_estrellas"},
    "Bosnia y Herzegovina": {"nombre": "Bosnia y Herzegovina", "code": "ba", "grupo": "soles_y_estrellas"},
    "Micronesia": {"nombre": "Micronesia", "code": "fm", "grupo": "soles_y_estrellas"},
    "Turquia": {"nombre": "Turquía", "code": "tr", "grupo": "media_luna_estrella"},
    "Tunez": {"nombre": "Túnez", "code": "tn", "grupo": "media_luna_estrella"},
    "Libia": {"nombre": "Libia", "code": "ly", "grupo": "media_luna_estrella"},
    "Azerbaiyan": {"nombre": "Azerbaiyán", "code": "az", "grupo": "media_luna_estrella"},
    "China": {"nombre": "China", "code": "cn", "grupo": "rojo_unicolor_o_predominante"},
    "Vietnam": {"nombre": "Vietnam", "code": "vn", "grupo": "rojo_unicolor_o_predominante"},
    "Albania": {"nombre": "Albania", "code": "al", "grupo": "rojo_unicolor_o_predominante"},
    "Montenegro": {"nombre": "Montenegro", "code": "me", "grupo": "rojo_unicolor_o_predominante"},
    "Marruecos": {"nombre": "Marruecos", "code": "ma", "grupo": "rojo_unicolor_o_predominante"},
    "Kirguistan": {"nombre": "Kirguistán", "code": "kg", "grupo": "rojo_unicolor_o_predominante"},
    "Somalia": {"nombre": "Somalia", "code": "so", "grupo": "azul_unicolor_o_predominante"},
    "Republica Democratica del Congo": {"nombre": "R. D. del Congo", "code": "cd", "grupo": "azul_unicolor_o_predominante"},
    "Nauru": {"nombre": "Nauru", "code": "nr", "grupo": "azul_unicolor_o_predominante"},
    "Canada": {"nombre": "Canadá", "code": "ca", "grupo": "otros_disenos"},
    "Nepal": {"nombre": "Nepal", "code": "np", "grupo": "otros_disenos"},
    "Butan": {"nombre": "Bután", "code": "bt", "grupo": "otros_disenos"},
    "Sri Lanka": {"nombre": "Sri Lanka", "code": "lk", "grupo": "otros_disenos"},
    "Mongolia": {"nombre": "Mongolia", "code": "mn", "grupo": "otros_disenos"},
    "Camboya": {"nombre": "Camboya", "code": "kh", "grupo": "otros_disenos"},
    "Laos": {"nombre": "Laos", "code": "la", "grupo": "otros_disenos"},
    "Espana": {"nombre": "España", "code": "es", "grupo": "tres_franjas_horizontales"},
    "Portugal": {"nombre": "Portugal", "code": "pt", "grupo": "otros_disenos"},
    "Chipre": {"nombre": "Chipre", "code": "cy", "grupo": "otros_disenos"},
    "República Checa": {"nombre": "República Checa", "code": "cz", "grupo": "otros_disenos"},
    "Ucrania": {"nombre": "Ucrania", "code": "ua", "grupo": "azul_unicolor_o_predominante"},
    "Bielorrusia": {"nombre": "Bielorrusia", "code": "by", "grupo": "otros_disenos"},
    "Macedonia del Norte": {"nombre": "Macedonia del Norte", "code": "mk", "grupo": "otros_disenos"},
    "Georgia": {"nombre": "Georgia", "code": "ge", "grupo": "otros_disenos"},
    "Armenia": {"nombre": "Armenia", "code": "am", "grupo": "tres_franjas_horizontales"},
    "Libano": {"nombre": "Líbano", "code": "lb", "grupo": "otros_disenos"},
    "Oman": {"nombre": "Omán", "code": "om", "grupo": "arabe_tricolor_horizontal"},
    "Qatar": {"nombre": "Catar", "code": "qa", "grupo": "otros_disenos"},
    "Bahrein": {"nombre": "Baréin", "code": "bh", "grupo": "otros_disenos"},
    "Iran": {"nombre": "Irán", "code": "ir", "grupo": "tres_franjas_horizontales"},
    "Kazajistan": {"nombre": "Kazajistán", "code": "kz", "grupo": "azul_unicolor_o_predominante"},
    "Uzbekistan": {"nombre": "Uzbekistán", "code": "uz", "grupo": "verde_blanco_horizontal"},
    "Turkmenistan": {"nombre": "Turkmenistán", "code": "tm", "grupo": "verde_blanco_horizontal"},
    "Tayikistan": {"nombre": "Tayikistán", "code": "tj", "grupo": "verde_blanco_horizontal"},
    "Afganistan": {"nombre": "Afganistán", "code": "af", "grupo": "otros_disenos"},
    "Maldivas": {"nombre": "Maldivas", "code": "mv", "grupo": "otros_disenos"},
    "Corea del Norte": {"nombre": "Corea del Norte", "code": "kp", "grupo": "otros_disenos"},
    "Taiwan": {"nombre": "Taiwán", "code": "tw", "grupo": "otros_disenos"},
    "Filipinas": {"nombre": "Filipinas", "code": "ph", "grupo": "otros_disenos"},
    "Brunei": {"nombre": "Brunéi", "code": "bn", "grupo": "otros_disenos"},
    "Timor Oriental": {"nombre": "Timor Oriental", "code": "tl", "grupo": "otros_disenos"},
    "Papua Nueva Guinea": {"nombre": "Papua Nueva Guinea", "code": "pg", "grupo": "otros_disenos"},
    "Islas Salomon": {"nombre": "Islas Salomón", "code": "sb", "grupo": "soles_y_estrellas"},
    "Vanuatu": {"nombre": "Vanuatu", "code": "vu", "grupo": "otros_disenos"},
    "Tonga": {"nombre": "Tonga", "code": "to", "grupo": "rojo_unicolor_o_predominante"},
    "Samoa": {"nombre": "Samoa", "code": "ws", "grupo": "rojo_unicolor_o_predominante"},
    "Kiribati": {"nombre": "Kiribati", "code": "ki", "grupo": "otros_disenos"},
    "Islas Marshall": {"nombre": "Islas Marshall", "code": "mh", "grupo": "otros_disenos"},
    "Sahara Occidental": {"nombre": "Sahara Occidental", "code": "eh", "grupo": "arabe_tricolor_horizontal"},
    "Sudan del Sur": {"nombre": "Sudán del Sur", "code": "ss", "grupo": "arabe_tricolor_horizontal"},
    "Gambia": {"nombre": "Gambia", "code": "gm", "grupo": "tres_franjas_horizontales"},
    "Guinea-Bissau": {"nombre": "Guinea-Bisáu", "code": "gw", "grupo": "panafricano_verde_amarillo_rojo"},
    "Republica Centroafricana": {"nombre": "R. Centroafricana", "code": "cf", "grupo": "otros_disenos"},
    "Guinea Ecuatorial": {"nombre": "Guinea Ecuatorial", "code": "gq", "grupo": "tres_franjas_horizontales"},
    "Santo Tome y Principe": {"nombre": "Santo Tomé y Príncipe", "code": "st", "grupo": "otros_disenos"},
    "Eritrea": {"nombre": "Eritrea", "code": "er", "grupo": "otros_disenos"},
    "Etiopia": {"nombre": "Etiopía", "code": "et", "grupo": "otros_disenos"},
    "Yibuti": {"nombre": "Yibuti", "code": "dj", "grupo": "otros_disenos"},
    "Kenia": {"nombre": "Kenia", "code": "ke", "grupo": "otros_disenos"},
    "Ruanda": {"nombre": "Ruanda", "code": "rw", "grupo": "otros_disenos"},
    "Burundi": {"nombre": "Burundi", "code": "bi", "grupo": "otros_disenos"},
    "Tanzania": {"nombre": "Tanzania", "code": "tz", "grupo": "otros_disenos"},
    "Seychelles": {"nombre": "Seychelles", "code": "sc", "grupo": "otros_disenos"},
    "Zambia": {"nombre": "Zambia", "code": "zm", "grupo": "otros_disenos"},
    "Malawi": {"nombre": "Malaui", "code": "mw", "grupo": "tres_franjas_horizontales"},
    "Mozambique": {"nombre": "Mozambique", "code": "mz", "grupo": "otros_disenos"},
    "Zimbabwe": {"nombre": "Zimbabue", "code": "zw", "grupo": "otros_disenos"},
    "Botswana": {"nombre": "Botsuana", "code": "bw", "grupo": "tres_franjas_horizontales"},
    "Namibia": {"nombre": "Namibia", "code": "na", "grupo": "otros_disenos"},
    "Sudafrica": {"nombre": "Sudáfrica", "code": "za", "grupo": "otros_disenos"},
    "Lesoto": {"nombre": "Lesoto", "code": "ls", "grupo": "tres_franjas_horizontales"},
    "Eswatini": {"nombre": "Suazilandia", "code": "sz", "grupo": "otros_disenos"},
    "Madagascar": {"nombre": "Madagascar", "code": "mg", "grupo": "otros_disenos"},
    "Mauricio": {"nombre": "Mauricio", "code": "mu", "grupo": "tres_franjas_horizontales"},
    "Comoras": {"nombre": "Comoras", "code": "km", "grupo": "otros_disenos"},
    "Islandia": {"nombre": "Islandia", "code": "is", "grupo": "cruz_escandinava"},
    "Belice": {"nombre": "Belice", "code": "bz", "grupo": "otros_disenos"},
    "Panama": {"nombre": "Panamá", "code": "pa", "grupo": "otros_disenos"},
    "Bahamas": {"nombre": "Bahamas", "code": "bs", "grupo": "otros_disenos"},
    "Haiti": {"nombre": "Haití", "code": "ht", "grupo": "otros_disenos"},
    "Republica Dominicana": {"nombre": "R. Dominicana", "code": "do", "grupo": "otros_disenos"},
    "San Cristobal y Nieves": {"nombre": "San Cristóbal y Nieves", "code": "kn", "grupo": "otros_disenos"},
    "Antigua y Barbuda": {"nombre": "Antigua y Barbuda", "code": "ag", "grupo": "otros_disenos"},
    "Dominica": {"nombre": "Dominica", "code": "dm", "grupo": "otros_disenos"},
    "Santa Lucia": {"nombre": "Santa Lucía", "code": "lc", "grupo": "otros_disenos"},
    "San Vicente y las Granadinas": {"nombre": "San Vicente y Granadinas", "code": "vc", "grupo": "otros_disenos"},
    "Barbados": {"nombre": "Barbados", "code": "bb", "grupo": "otros_disenos"},
    "Granada": {"nombre": "Granada", "code": "gd", "grupo": "otros_disenos"},
    "Trinidad y Tobago": {"nombre": "Trinidad y Tobago", "code": "tt", "grupo": "otros_disenos"},
    "Guyana": {"nombre": "Guyana", "code": "gy", "grupo": "otros_disenos"},
    "Surinam": {"nombre": "Surinam", "code": "sr", "grupo": "otros_disenos"},
    "Chile": {"nombre": "Chile", "code": "cl", "grupo": "otros_disenos"}
}
